version: '2.2'

services:

  app:
    build: .
    command: ./scripts/docker-entrypoint.sh
    tty: true
    stdin_open: true
    depends_on:
      - 'db'
    volumes:
      - '.:/app'
    ports:
      - "3000:3000"
    tmpfs:
      - "/var/tmp"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=trails
      - DATABASE_PASSWORD=trails
      - MAPBOX_API_TOKEN=${MAPBOX_API_TOKEN}
  db:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_USER=trails
      - POSTGRES_PASS=trails
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      #- POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    ports:
      - 5434:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"


  redis:
    image: redis:2.8
    ports:
      - '6379:6379'
volumes:
  postgis-data: