version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: ls
          command: ls -lsa
      - run:
          name: Compose build
          command: docker-compose build
      - run:
          name: Compose up
          command: docker-compose up -d
      - run:
          name: Bootstrap
          command: scripts/boostrap.sh
      - run:
          name: Lint
          command: scripts/lint.sh
