version: 2.1

jobs:
  build:
    machine: true
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Compose build
          command: docker-compose build
      - run:
          name: Bootstrap
          command: ./scripts/boostrap.sh
      - run:
          name: Lint
          command: ./scripts/lint.sh
